import { Metadata } from "next";
import { constructMetadata } from "@/lib/seo";
import { Container } from "@/components/ui/Container";

export const metadata: Metadata = constructMetadata({
  title: "Terms & Conditions | Fivefold Renewable",
  description: "Terms & Conditions for Fivefold Renewable Pvt. Ltd.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <div className="pt-24 sm:pt-32 pb-20">
      <Container className="max-w-4xl space-y-6">
        <h1 className="font-heading text-4xl font-extrabold text-brand-charcoal">
          Terms & Conditions
        </h1>
        <p className="text-sm text-slate-500">Last updated: August 2026</p>

        <div className="prose prose-slate max-w-none space-y-4 text-slate-600 text-sm leading-relaxed">
          <p>
            Welcome to fivefoldsolar.com, operated by Fivefold Renewable Pvt. Ltd. By accessing or using this website, you agree to comply with and be bound by the following terms.
          </p>

          <h2 className="font-heading text-lg font-bold text-brand-charcoal pt-2">
            1. Preliminary Estimates & Calculator Disclaimers
          </h2>
          <p>
            All figures, capacity calculations, estimated annual energy generation numbers, payback periods, and financial savings generated by self-service tools or calculators on this site are indicative preliminary draft estimates for guidance only. Final plant capacity, PVsyst generation simulations, and commercial terms are subject to formal site audit, 3D shadow analysis, and written contract execution.
          </p>

          <h2 className="font-heading text-lg font-bold text-brand-charcoal pt-2">
            2. Government Subsidies & Regulatory Compliance
          </h2>
          <p>
            Government schemes (such as PM Surya Ghar Muft Bijli Yojana) and net metering approvals are governed by prevailing Central MNRE and State DISCOM regulations. Fivefold Renewable facilitates application documentation but does not warrant third-party government subsidy disbursements or statutory timelines.
          </p>

          <h2 className="font-heading text-lg font-bold text-brand-charcoal pt-2">
            3. Intellectual Property
          </h2>
          <p>
            All content, engineering graphics, branding, text, and layout designs presented on this website are the intellectual property of Fivefold Renewable Pvt. Ltd.
          </p>
        </div>
      </Container>
    </div>
  );
}
